spring:
    datasource:
        username: SpringUser
        password: Secret
        url: "jdbc:mysql://localhost:3306/incident_db"
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        generate-ddl: true
    
